package com.jbit.entity;

import com.jbit.dao.AsAccount;

public interface AsAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_account
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_account
     *
     * @mbggenerated
     */
    int insert(AsAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_account
     *
     * @mbggenerated
     */
    int insertSelective(AsAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_account
     *
     * @mbggenerated
     */
    AsAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AsAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AsAccount record);
}