package com.jbit.entity;

import com.jbit.dao.AsContacts;

public interface AsContactsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_contacts
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_contacts
     *
     * @mbggenerated
     */
    int insert(AsContacts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_contacts
     *
     * @mbggenerated
     */
    int insertSelective(AsContacts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_contacts
     *
     * @mbggenerated
     */
    AsContacts selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_contacts
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AsContacts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_contacts
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AsContacts record);
}