package com.jbit.entity;

import com.jbit.dao.AsKeywords;
import com.jbit.dao.AsKeywordsWithBLOBs;

public interface AsKeywordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_keywords
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_keywords
     *
     * @mbggenerated
     */
    int insert(AsKeywordsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_keywords
     *
     * @mbggenerated
     */
    int insertSelective(AsKeywordsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_keywords
     *
     * @mbggenerated
     */
    AsKeywordsWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_keywords
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AsKeywordsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_keywords
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(AsKeywordsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_keywords
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AsKeywords record);
}