package com.jbit.entity;

import com.jbit.dao.AsRole;

public interface AsRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_role
     *
     * @mbggenerated
     */
    int insert(AsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_role
     *
     * @mbggenerated
     */
    int insertSelective(AsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_role
     *
     * @mbggenerated
     */
    AsRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AsRole record);
}