package com.jbit.entity;

import com.jbit.dao.HatArea;

public interface HatAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_area
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_area
     *
     * @mbggenerated
     */
    int insert(HatArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_area
     *
     * @mbggenerated
     */
    int insertSelective(HatArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_area
     *
     * @mbggenerated
     */
    HatArea selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_area
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HatArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_area
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HatArea record);
}