package com.jbit.entity;

import com.jbit.dao.HatCity;

public interface HatCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_city
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_city
     *
     * @mbggenerated
     */
    int insert(HatCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_city
     *
     * @mbggenerated
     */
    int insertSelective(HatCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_city
     *
     * @mbggenerated
     */
    HatCity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_city
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HatCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_city
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HatCity record);
}