package com.jbit.entity;

import com.jbit.dao.HatProvince;

public interface HatProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_province
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_province
     *
     * @mbggenerated
     */
    int insert(HatProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_province
     *
     * @mbggenerated
     */
    int insertSelective(HatProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_province
     *
     * @mbggenerated
     */
    HatProvince selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_province
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HatProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_province
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HatProvince record);
}