package com.jbit.dao;

public class AsAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_account.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_account.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_account.money
     *
     * @mbggenerated
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_account.moneyBak
     *
     * @mbggenerated
     */
    private Double moneybak;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_account.id
     *
     * @return the value of as_account.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_account.id
     *
     * @param id the value for as_account.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_account.userId
     *
     * @return the value of as_account.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_account.userId
     *
     * @param userid the value for as_account.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_account.money
     *
     * @return the value of as_account.money
     *
     * @mbggenerated
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_account.money
     *
     * @param money the value for as_account.money
     *
     * @mbggenerated
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_account.moneyBak
     *
     * @return the value of as_account.moneyBak
     *
     * @mbggenerated
     */
    public Double getMoneybak() {
        return moneybak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_account.moneyBak
     *
     * @param moneybak the value for as_account.moneyBak
     *
     * @mbggenerated
     */
    public void setMoneybak(Double moneybak) {
        this.moneybak = moneybak;
    }
}