package com.jbit.dao;

public class AsContacts {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_contacts.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_contacts.customId
     *
     * @mbggenerated
     */
    private Integer customid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_contacts.contactName
     *
     * @mbggenerated
     */
    private String contactname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_contacts.contactTel
     *
     * @mbggenerated
     */
    private String contacttel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_contacts.contactFax
     *
     * @mbggenerated
     */
    private String contactfax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_contacts.contactEmail
     *
     * @mbggenerated
     */
    private String contactemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_contacts.contactRole
     *
     * @mbggenerated
     */
    private String contactrole;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_contacts.id
     *
     * @return the value of as_contacts.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_contacts.id
     *
     * @param id the value for as_contacts.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_contacts.customId
     *
     * @return the value of as_contacts.customId
     *
     * @mbggenerated
     */
    public Integer getCustomid() {
        return customid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_contacts.customId
     *
     * @param customid the value for as_contacts.customId
     *
     * @mbggenerated
     */
    public void setCustomid(Integer customid) {
        this.customid = customid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_contacts.contactName
     *
     * @return the value of as_contacts.contactName
     *
     * @mbggenerated
     */
    public String getContactname() {
        return contactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_contacts.contactName
     *
     * @param contactname the value for as_contacts.contactName
     *
     * @mbggenerated
     */
    public void setContactname(String contactname) {
        this.contactname = contactname == null ? null : contactname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_contacts.contactTel
     *
     * @return the value of as_contacts.contactTel
     *
     * @mbggenerated
     */
    public String getContacttel() {
        return contacttel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_contacts.contactTel
     *
     * @param contacttel the value for as_contacts.contactTel
     *
     * @mbggenerated
     */
    public void setContacttel(String contacttel) {
        this.contacttel = contacttel == null ? null : contacttel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_contacts.contactFax
     *
     * @return the value of as_contacts.contactFax
     *
     * @mbggenerated
     */
    public String getContactfax() {
        return contactfax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_contacts.contactFax
     *
     * @param contactfax the value for as_contacts.contactFax
     *
     * @mbggenerated
     */
    public void setContactfax(String contactfax) {
        this.contactfax = contactfax == null ? null : contactfax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_contacts.contactEmail
     *
     * @return the value of as_contacts.contactEmail
     *
     * @mbggenerated
     */
    public String getContactemail() {
        return contactemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_contacts.contactEmail
     *
     * @param contactemail the value for as_contacts.contactEmail
     *
     * @mbggenerated
     */
    public void setContactemail(String contactemail) {
        this.contactemail = contactemail == null ? null : contactemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_contacts.contactRole
     *
     * @return the value of as_contacts.contactRole
     *
     * @mbggenerated
     */
    public String getContactrole() {
        return contactrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_contacts.contactRole
     *
     * @param contactrole the value for as_contacts.contactRole
     *
     * @mbggenerated
     */
    public void setContactrole(String contactrole) {
        this.contactrole = contactrole == null ? null : contactrole.trim();
    }
}