package com.jbit.dao;

import java.util.Date;

public class AsCustoms {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.agentId
     *
     * @mbggenerated
     */
    private Integer agentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.provinceName
     *
     * @mbggenerated
     */
    private String provincename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.cityName
     *
     * @mbggenerated
     */
    private String cityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.areaName
     *
     * @mbggenerated
     */
    private String areaname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.customType
     *
     * @mbggenerated
     */
    private String customtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.cardType
     *
     * @mbggenerated
     */
    private String cardtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.customName
     *
     * @mbggenerated
     */
    private String customname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.siteUrl
     *
     * @mbggenerated
     */
    private String siteurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.customStatus
     *
     * @mbggenerated
     */
    private Integer customstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.bossName
     *
     * @mbggenerated
     */
    private String bossname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.cardNum
     *
     * @mbggenerated
     */
    private String cardnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.companyTel
     *
     * @mbggenerated
     */
    private String companytel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.companyFax
     *
     * @mbggenerated
     */
    private String companyfax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.regDatetime
     *
     * @mbggenerated
     */
    private Date regdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.country
     *
     * @mbggenerated
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.companyAddress
     *
     * @mbggenerated
     */
    private String companyaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.remark1
     *
     * @mbggenerated
     */
    private String remark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.remark2
     *
     * @mbggenerated
     */
    private String remark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.remark3
     *
     * @mbggenerated
     */
    private String remark3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.id
     *
     * @return the value of as_customs.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.id
     *
     * @param id the value for as_customs.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.agentId
     *
     * @return the value of as_customs.agentId
     *
     * @mbggenerated
     */
    public Integer getAgentid() {
        return agentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.agentId
     *
     * @param agentid the value for as_customs.agentId
     *
     * @mbggenerated
     */
    public void setAgentid(Integer agentid) {
        this.agentid = agentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.provinceName
     *
     * @return the value of as_customs.provinceName
     *
     * @mbggenerated
     */
    public String getProvincename() {
        return provincename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.provinceName
     *
     * @param provincename the value for as_customs.provinceName
     *
     * @mbggenerated
     */
    public void setProvincename(String provincename) {
        this.provincename = provincename == null ? null : provincename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.cityName
     *
     * @return the value of as_customs.cityName
     *
     * @mbggenerated
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.cityName
     *
     * @param cityname the value for as_customs.cityName
     *
     * @mbggenerated
     */
    public void setCityname(String cityname) {
        this.cityname = cityname == null ? null : cityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.areaName
     *
     * @return the value of as_customs.areaName
     *
     * @mbggenerated
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.areaName
     *
     * @param areaname the value for as_customs.areaName
     *
     * @mbggenerated
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname == null ? null : areaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.customType
     *
     * @return the value of as_customs.customType
     *
     * @mbggenerated
     */
    public String getCustomtype() {
        return customtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.customType
     *
     * @param customtype the value for as_customs.customType
     *
     * @mbggenerated
     */
    public void setCustomtype(String customtype) {
        this.customtype = customtype == null ? null : customtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.cardType
     *
     * @return the value of as_customs.cardType
     *
     * @mbggenerated
     */
    public String getCardtype() {
        return cardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.cardType
     *
     * @param cardtype the value for as_customs.cardType
     *
     * @mbggenerated
     */
    public void setCardtype(String cardtype) {
        this.cardtype = cardtype == null ? null : cardtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.customName
     *
     * @return the value of as_customs.customName
     *
     * @mbggenerated
     */
    public String getCustomname() {
        return customname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.customName
     *
     * @param customname the value for as_customs.customName
     *
     * @mbggenerated
     */
    public void setCustomname(String customname) {
        this.customname = customname == null ? null : customname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.siteUrl
     *
     * @return the value of as_customs.siteUrl
     *
     * @mbggenerated
     */
    public String getSiteurl() {
        return siteurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.siteUrl
     *
     * @param siteurl the value for as_customs.siteUrl
     *
     * @mbggenerated
     */
    public void setSiteurl(String siteurl) {
        this.siteurl = siteurl == null ? null : siteurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.customStatus
     *
     * @return the value of as_customs.customStatus
     *
     * @mbggenerated
     */
    public Integer getCustomstatus() {
        return customstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.customStatus
     *
     * @param customstatus the value for as_customs.customStatus
     *
     * @mbggenerated
     */
    public void setCustomstatus(Integer customstatus) {
        this.customstatus = customstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.bossName
     *
     * @return the value of as_customs.bossName
     *
     * @mbggenerated
     */
    public String getBossname() {
        return bossname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.bossName
     *
     * @param bossname the value for as_customs.bossName
     *
     * @mbggenerated
     */
    public void setBossname(String bossname) {
        this.bossname = bossname == null ? null : bossname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.cardNum
     *
     * @return the value of as_customs.cardNum
     *
     * @mbggenerated
     */
    public String getCardnum() {
        return cardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.cardNum
     *
     * @param cardnum the value for as_customs.cardNum
     *
     * @mbggenerated
     */
    public void setCardnum(String cardnum) {
        this.cardnum = cardnum == null ? null : cardnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.companyTel
     *
     * @return the value of as_customs.companyTel
     *
     * @mbggenerated
     */
    public String getCompanytel() {
        return companytel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.companyTel
     *
     * @param companytel the value for as_customs.companyTel
     *
     * @mbggenerated
     */
    public void setCompanytel(String companytel) {
        this.companytel = companytel == null ? null : companytel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.companyFax
     *
     * @return the value of as_customs.companyFax
     *
     * @mbggenerated
     */
    public String getCompanyfax() {
        return companyfax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.companyFax
     *
     * @param companyfax the value for as_customs.companyFax
     *
     * @mbggenerated
     */
    public void setCompanyfax(String companyfax) {
        this.companyfax = companyfax == null ? null : companyfax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.regDatetime
     *
     * @return the value of as_customs.regDatetime
     *
     * @mbggenerated
     */
    public Date getRegdatetime() {
        return regdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.regDatetime
     *
     * @param regdatetime the value for as_customs.regDatetime
     *
     * @mbggenerated
     */
    public void setRegdatetime(Date regdatetime) {
        this.regdatetime = regdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.country
     *
     * @return the value of as_customs.country
     *
     * @mbggenerated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.country
     *
     * @param country the value for as_customs.country
     *
     * @mbggenerated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.companyAddress
     *
     * @return the value of as_customs.companyAddress
     *
     * @mbggenerated
     */
    public String getCompanyaddress() {
        return companyaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.companyAddress
     *
     * @param companyaddress the value for as_customs.companyAddress
     *
     * @mbggenerated
     */
    public void setCompanyaddress(String companyaddress) {
        this.companyaddress = companyaddress == null ? null : companyaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.memo
     *
     * @return the value of as_customs.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.memo
     *
     * @param memo the value for as_customs.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.remark1
     *
     * @return the value of as_customs.remark1
     *
     * @mbggenerated
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.remark1
     *
     * @param remark1 the value for as_customs.remark1
     *
     * @mbggenerated
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.remark2
     *
     * @return the value of as_customs.remark2
     *
     * @mbggenerated
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.remark2
     *
     * @param remark2 the value for as_customs.remark2
     *
     * @mbggenerated
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.remark3
     *
     * @return the value of as_customs.remark3
     *
     * @mbggenerated
     */
    public String getRemark3() {
        return remark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.remark3
     *
     * @param remark3 the value for as_customs.remark3
     *
     * @mbggenerated
     */
    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }
}