package com.jbit.dao;

import java.util.Date;

public class AsFunction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_function.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_function.parentId
     *
     * @mbggenerated
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_function.functionCode
     *
     * @mbggenerated
     */
    private String functioncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_function.functionName
     *
     * @mbggenerated
     */
    private String functionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_function.creationTime
     *
     * @mbggenerated
     */
    private Date creationtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_function.createdBy
     *
     * @mbggenerated
     */
    private String createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_function.lastUpdateTime
     *
     * @mbggenerated
     */
    private Date lastupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_function.isStart
     *
     * @mbggenerated
     */
    private Integer isstart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_function.sortnum
     *
     * @mbggenerated
     */
    private Integer sortnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_function.funcUrl
     *
     * @mbggenerated
     */
    private String funcurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_function.id
     *
     * @return the value of as_function.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_function.id
     *
     * @param id the value for as_function.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_function.parentId
     *
     * @return the value of as_function.parentId
     *
     * @mbggenerated
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_function.parentId
     *
     * @param parentid the value for as_function.parentId
     *
     * @mbggenerated
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_function.functionCode
     *
     * @return the value of as_function.functionCode
     *
     * @mbggenerated
     */
    public String getFunctioncode() {
        return functioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_function.functionCode
     *
     * @param functioncode the value for as_function.functionCode
     *
     * @mbggenerated
     */
    public void setFunctioncode(String functioncode) {
        this.functioncode = functioncode == null ? null : functioncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_function.functionName
     *
     * @return the value of as_function.functionName
     *
     * @mbggenerated
     */
    public String getFunctionname() {
        return functionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_function.functionName
     *
     * @param functionname the value for as_function.functionName
     *
     * @mbggenerated
     */
    public void setFunctionname(String functionname) {
        this.functionname = functionname == null ? null : functionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_function.creationTime
     *
     * @return the value of as_function.creationTime
     *
     * @mbggenerated
     */
    public Date getCreationtime() {
        return creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_function.creationTime
     *
     * @param creationtime the value for as_function.creationTime
     *
     * @mbggenerated
     */
    public void setCreationtime(Date creationtime) {
        this.creationtime = creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_function.createdBy
     *
     * @return the value of as_function.createdBy
     *
     * @mbggenerated
     */
    public String getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_function.createdBy
     *
     * @param createdby the value for as_function.createdBy
     *
     * @mbggenerated
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby == null ? null : createdby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_function.lastUpdateTime
     *
     * @return the value of as_function.lastUpdateTime
     *
     * @mbggenerated
     */
    public Date getLastupdatetime() {
        return lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_function.lastUpdateTime
     *
     * @param lastupdatetime the value for as_function.lastUpdateTime
     *
     * @mbggenerated
     */
    public void setLastupdatetime(Date lastupdatetime) {
        this.lastupdatetime = lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_function.isStart
     *
     * @return the value of as_function.isStart
     *
     * @mbggenerated
     */
    public Integer getIsstart() {
        return isstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_function.isStart
     *
     * @param isstart the value for as_function.isStart
     *
     * @mbggenerated
     */
    public void setIsstart(Integer isstart) {
        this.isstart = isstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_function.sortnum
     *
     * @return the value of as_function.sortnum
     *
     * @mbggenerated
     */
    public Integer getSortnum() {
        return sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_function.sortnum
     *
     * @param sortnum the value for as_function.sortnum
     *
     * @mbggenerated
     */
    public void setSortnum(Integer sortnum) {
        this.sortnum = sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_function.funcUrl
     *
     * @return the value of as_function.funcUrl
     *
     * @mbggenerated
     */
    public String getFuncurl() {
        return funcurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_function.funcUrl
     *
     * @param funcurl the value for as_function.funcUrl
     *
     * @mbggenerated
     */
    public void setFuncurl(String funcurl) {
        this.funcurl = funcurl == null ? null : funcurl.trim();
    }
}