package com.jbit.dao;

import java.util.Date;

public class AsKeywords {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.systemconfigId
     *
     * @mbggenerated
     */
    private Integer systemconfigid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.customId
     *
     * @mbggenerated
     */
    private Integer customid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.agentId
     *
     * @mbggenerated
     */
    private Integer agentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.preRegFrozenMoney
     *
     * @mbggenerated
     */
    private Double preregfrozenmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.price
     *
     * @mbggenerated
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.openApp
     *
     * @mbggenerated
     */
    private Integer openapp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.appUserName
     *
     * @mbggenerated
     */
    private String appusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.appPassword
     *
     * @mbggenerated
     */
    private String apppassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.preRegDatetime
     *
     * @mbggenerated
     */
    private Date preregdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.preRegPassDatetime
     *
     * @mbggenerated
     */
    private Date preregpassdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.regDatetime
     *
     * @mbggenerated
     */
    private Date regdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.regPassDatetime
     *
     * @mbggenerated
     */
    private Date regpassdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.isPass
     *
     * @mbggenerated
     */
    private Integer ispass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.checkStatus
     *
     * @mbggenerated
     */
    private Integer checkstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.isUse
     *
     * @mbggenerated
     */
    private Integer isuse;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.id
     *
     * @return the value of as_keywords.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.id
     *
     * @param id the value for as_keywords.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.systemconfigId
     *
     * @return the value of as_keywords.systemconfigId
     *
     * @mbggenerated
     */
    public Integer getSystemconfigid() {
        return systemconfigid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.systemconfigId
     *
     * @param systemconfigid the value for as_keywords.systemconfigId
     *
     * @mbggenerated
     */
    public void setSystemconfigid(Integer systemconfigid) {
        this.systemconfigid = systemconfigid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.customId
     *
     * @return the value of as_keywords.customId
     *
     * @mbggenerated
     */
    public Integer getCustomid() {
        return customid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.customId
     *
     * @param customid the value for as_keywords.customId
     *
     * @mbggenerated
     */
    public void setCustomid(Integer customid) {
        this.customid = customid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.agentId
     *
     * @return the value of as_keywords.agentId
     *
     * @mbggenerated
     */
    public Integer getAgentid() {
        return agentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.agentId
     *
     * @param agentid the value for as_keywords.agentId
     *
     * @mbggenerated
     */
    public void setAgentid(Integer agentid) {
        this.agentid = agentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.preRegFrozenMoney
     *
     * @return the value of as_keywords.preRegFrozenMoney
     *
     * @mbggenerated
     */
    public Double getPreregfrozenmoney() {
        return preregfrozenmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.preRegFrozenMoney
     *
     * @param preregfrozenmoney the value for as_keywords.preRegFrozenMoney
     *
     * @mbggenerated
     */
    public void setPreregfrozenmoney(Double preregfrozenmoney) {
        this.preregfrozenmoney = preregfrozenmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.price
     *
     * @return the value of as_keywords.price
     *
     * @mbggenerated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.price
     *
     * @param price the value for as_keywords.price
     *
     * @mbggenerated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.openApp
     *
     * @return the value of as_keywords.openApp
     *
     * @mbggenerated
     */
    public Integer getOpenapp() {
        return openapp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.openApp
     *
     * @param openapp the value for as_keywords.openApp
     *
     * @mbggenerated
     */
    public void setOpenapp(Integer openapp) {
        this.openapp = openapp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.appUserName
     *
     * @return the value of as_keywords.appUserName
     *
     * @mbggenerated
     */
    public String getAppusername() {
        return appusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.appUserName
     *
     * @param appusername the value for as_keywords.appUserName
     *
     * @mbggenerated
     */
    public void setAppusername(String appusername) {
        this.appusername = appusername == null ? null : appusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.appPassword
     *
     * @return the value of as_keywords.appPassword
     *
     * @mbggenerated
     */
    public String getApppassword() {
        return apppassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.appPassword
     *
     * @param apppassword the value for as_keywords.appPassword
     *
     * @mbggenerated
     */
    public void setApppassword(String apppassword) {
        this.apppassword = apppassword == null ? null : apppassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.preRegDatetime
     *
     * @return the value of as_keywords.preRegDatetime
     *
     * @mbggenerated
     */
    public Date getPreregdatetime() {
        return preregdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.preRegDatetime
     *
     * @param preregdatetime the value for as_keywords.preRegDatetime
     *
     * @mbggenerated
     */
    public void setPreregdatetime(Date preregdatetime) {
        this.preregdatetime = preregdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.preRegPassDatetime
     *
     * @return the value of as_keywords.preRegPassDatetime
     *
     * @mbggenerated
     */
    public Date getPreregpassdatetime() {
        return preregpassdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.preRegPassDatetime
     *
     * @param preregpassdatetime the value for as_keywords.preRegPassDatetime
     *
     * @mbggenerated
     */
    public void setPreregpassdatetime(Date preregpassdatetime) {
        this.preregpassdatetime = preregpassdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.regDatetime
     *
     * @return the value of as_keywords.regDatetime
     *
     * @mbggenerated
     */
    public Date getRegdatetime() {
        return regdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.regDatetime
     *
     * @param regdatetime the value for as_keywords.regDatetime
     *
     * @mbggenerated
     */
    public void setRegdatetime(Date regdatetime) {
        this.regdatetime = regdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.regPassDatetime
     *
     * @return the value of as_keywords.regPassDatetime
     *
     * @mbggenerated
     */
    public Date getRegpassdatetime() {
        return regpassdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.regPassDatetime
     *
     * @param regpassdatetime the value for as_keywords.regPassDatetime
     *
     * @mbggenerated
     */
    public void setRegpassdatetime(Date regpassdatetime) {
        this.regpassdatetime = regpassdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.isPass
     *
     * @return the value of as_keywords.isPass
     *
     * @mbggenerated
     */
    public Integer getIspass() {
        return ispass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.isPass
     *
     * @param ispass the value for as_keywords.isPass
     *
     * @mbggenerated
     */
    public void setIspass(Integer ispass) {
        this.ispass = ispass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.checkStatus
     *
     * @return the value of as_keywords.checkStatus
     *
     * @mbggenerated
     */
    public Integer getCheckstatus() {
        return checkstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.checkStatus
     *
     * @param checkstatus the value for as_keywords.checkStatus
     *
     * @mbggenerated
     */
    public void setCheckstatus(Integer checkstatus) {
        this.checkstatus = checkstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.isUse
     *
     * @return the value of as_keywords.isUse
     *
     * @mbggenerated
     */
    public Integer getIsuse() {
        return isuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.isUse
     *
     * @param isuse the value for as_keywords.isUse
     *
     * @mbggenerated
     */
    public void setIsuse(Integer isuse) {
        this.isuse = isuse;
    }
}