package com.jbit.dao;

public class AsKeywordsWithBLOBs extends AsKeywords {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.keywords
     *
     * @mbggenerated
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.loginUrl
     *
     * @mbggenerated
     */
    private String loginurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.iosDownloadUrl
     *
     * @mbggenerated
     */
    private String iosdownloadurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.androidDownloadUrl
     *
     * @mbggenerated
     */
    private String androiddownloadurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.codeIosUrl
     *
     * @mbggenerated
     */
    private String codeiosurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.codeAndroidUrl
     *
     * @mbggenerated
     */
    private String codeandroidurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.keywords
     *
     * @return the value of as_keywords.keywords
     *
     * @mbggenerated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.keywords
     *
     * @param keywords the value for as_keywords.keywords
     *
     * @mbggenerated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.loginUrl
     *
     * @return the value of as_keywords.loginUrl
     *
     * @mbggenerated
     */
    public String getLoginurl() {
        return loginurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.loginUrl
     *
     * @param loginurl the value for as_keywords.loginUrl
     *
     * @mbggenerated
     */
    public void setLoginurl(String loginurl) {
        this.loginurl = loginurl == null ? null : loginurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.iosDownloadUrl
     *
     * @return the value of as_keywords.iosDownloadUrl
     *
     * @mbggenerated
     */
    public String getIosdownloadurl() {
        return iosdownloadurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.iosDownloadUrl
     *
     * @param iosdownloadurl the value for as_keywords.iosDownloadUrl
     *
     * @mbggenerated
     */
    public void setIosdownloadurl(String iosdownloadurl) {
        this.iosdownloadurl = iosdownloadurl == null ? null : iosdownloadurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.androidDownloadUrl
     *
     * @return the value of as_keywords.androidDownloadUrl
     *
     * @mbggenerated
     */
    public String getAndroiddownloadurl() {
        return androiddownloadurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.androidDownloadUrl
     *
     * @param androiddownloadurl the value for as_keywords.androidDownloadUrl
     *
     * @mbggenerated
     */
    public void setAndroiddownloadurl(String androiddownloadurl) {
        this.androiddownloadurl = androiddownloadurl == null ? null : androiddownloadurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.codeIosUrl
     *
     * @return the value of as_keywords.codeIosUrl
     *
     * @mbggenerated
     */
    public String getCodeiosurl() {
        return codeiosurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.codeIosUrl
     *
     * @param codeiosurl the value for as_keywords.codeIosUrl
     *
     * @mbggenerated
     */
    public void setCodeiosurl(String codeiosurl) {
        this.codeiosurl = codeiosurl == null ? null : codeiosurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.codeAndroidUrl
     *
     * @return the value of as_keywords.codeAndroidUrl
     *
     * @mbggenerated
     */
    public String getCodeandroidurl() {
        return codeandroidurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.codeAndroidUrl
     *
     * @param codeandroidurl the value for as_keywords.codeAndroidUrl
     *
     * @mbggenerated
     */
    public void setCodeandroidurl(String codeandroidurl) {
        this.codeandroidurl = codeandroidurl == null ? null : codeandroidurl.trim();
    }
}