package com.jbit.dao;

import java.util.Date;

public class AsLogs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_logs.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_logs.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_logs.operateDatetime
     *
     * @mbggenerated
     */
    private Date operatedatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_logs.id
     *
     * @return the value of as_logs.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_logs.id
     *
     * @param id the value for as_logs.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_logs.userId
     *
     * @return the value of as_logs.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_logs.userId
     *
     * @param userid the value for as_logs.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_logs.operateDatetime
     *
     * @return the value of as_logs.operateDatetime
     *
     * @mbggenerated
     */
    public Date getOperatedatetime() {
        return operatedatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_logs.operateDatetime
     *
     * @param operatedatetime the value for as_logs.operateDatetime
     *
     * @mbggenerated
     */
    public void setOperatedatetime(Date operatedatetime) {
        this.operatedatetime = operatedatetime;
    }
}