package com.jbit.dao;

public class AsLogsWithBLOBs extends AsLogs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_logs.operateInfo
     *
     * @mbggenerated
     */
    private String operateinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_logs.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_logs.operateInfo
     *
     * @return the value of as_logs.operateInfo
     *
     * @mbggenerated
     */
    public String getOperateinfo() {
        return operateinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_logs.operateInfo
     *
     * @param operateinfo the value for as_logs.operateInfo
     *
     * @mbggenerated
     */
    public void setOperateinfo(String operateinfo) {
        this.operateinfo = operateinfo == null ? null : operateinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_logs.remark
     *
     * @return the value of as_logs.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_logs.remark
     *
     * @param remark the value for as_logs.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}