package com.jbit.dao;

import java.util.Date;

public class AsRolePremission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_role_premission.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_role_premission.roleId
     *
     * @mbggenerated
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_role_premission.functionId
     *
     * @mbggenerated
     */
    private Integer functionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_role_premission.creationTime
     *
     * @mbggenerated
     */
    private Date creationtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_role_premission.createdBy
     *
     * @mbggenerated
     */
    private String createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_role_premission.lastUpdateTime
     *
     * @mbggenerated
     */
    private Date lastupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_role_premission.isStart
     *
     * @mbggenerated
     */
    private Integer isstart;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_role_premission.id
     *
     * @return the value of as_role_premission.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_role_premission.id
     *
     * @param id the value for as_role_premission.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_role_premission.roleId
     *
     * @return the value of as_role_premission.roleId
     *
     * @mbggenerated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_role_premission.roleId
     *
     * @param roleid the value for as_role_premission.roleId
     *
     * @mbggenerated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_role_premission.functionId
     *
     * @return the value of as_role_premission.functionId
     *
     * @mbggenerated
     */
    public Integer getFunctionid() {
        return functionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_role_premission.functionId
     *
     * @param functionid the value for as_role_premission.functionId
     *
     * @mbggenerated
     */
    public void setFunctionid(Integer functionid) {
        this.functionid = functionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_role_premission.creationTime
     *
     * @return the value of as_role_premission.creationTime
     *
     * @mbggenerated
     */
    public Date getCreationtime() {
        return creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_role_premission.creationTime
     *
     * @param creationtime the value for as_role_premission.creationTime
     *
     * @mbggenerated
     */
    public void setCreationtime(Date creationtime) {
        this.creationtime = creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_role_premission.createdBy
     *
     * @return the value of as_role_premission.createdBy
     *
     * @mbggenerated
     */
    public String getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_role_premission.createdBy
     *
     * @param createdby the value for as_role_premission.createdBy
     *
     * @mbggenerated
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby == null ? null : createdby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_role_premission.lastUpdateTime
     *
     * @return the value of as_role_premission.lastUpdateTime
     *
     * @mbggenerated
     */
    public Date getLastupdatetime() {
        return lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_role_premission.lastUpdateTime
     *
     * @param lastupdatetime the value for as_role_premission.lastUpdateTime
     *
     * @mbggenerated
     */
    public void setLastupdatetime(Date lastupdatetime) {
        this.lastupdatetime = lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_role_premission.isStart
     *
     * @return the value of as_role_premission.isStart
     *
     * @mbggenerated
     */
    public Integer getIsstart() {
        return isstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_role_premission.isStart
     *
     * @param isstart the value for as_role_premission.isStart
     *
     * @mbggenerated
     */
    public void setIsstart(Integer isstart) {
        this.isstart = isstart;
    }
}