package com.jbit.dao;

import java.util.Date;

public class AsRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_role.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_role.roleName
     *
     * @mbggenerated
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_role.creationTime
     *
     * @mbggenerated
     */
    private Date creationtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_role.createdBy
     *
     * @mbggenerated
     */
    private String createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_role.lastUpdateTime
     *
     * @mbggenerated
     */
    private Date lastupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_role.isStart
     *
     * @mbggenerated
     */
    private Integer isstart;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_role.id
     *
     * @return the value of as_role.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_role.id
     *
     * @param id the value for as_role.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_role.roleName
     *
     * @return the value of as_role.roleName
     *
     * @mbggenerated
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_role.roleName
     *
     * @param rolename the value for as_role.roleName
     *
     * @mbggenerated
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_role.creationTime
     *
     * @return the value of as_role.creationTime
     *
     * @mbggenerated
     */
    public Date getCreationtime() {
        return creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_role.creationTime
     *
     * @param creationtime the value for as_role.creationTime
     *
     * @mbggenerated
     */
    public void setCreationtime(Date creationtime) {
        this.creationtime = creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_role.createdBy
     *
     * @return the value of as_role.createdBy
     *
     * @mbggenerated
     */
    public String getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_role.createdBy
     *
     * @param createdby the value for as_role.createdBy
     *
     * @mbggenerated
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby == null ? null : createdby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_role.lastUpdateTime
     *
     * @return the value of as_role.lastUpdateTime
     *
     * @mbggenerated
     */
    public Date getLastupdatetime() {
        return lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_role.lastUpdateTime
     *
     * @param lastupdatetime the value for as_role.lastUpdateTime
     *
     * @mbggenerated
     */
    public void setLastupdatetime(Date lastupdatetime) {
        this.lastupdatetime = lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_role.isStart
     *
     * @return the value of as_role.isStart
     *
     * @mbggenerated
     */
    public Integer getIsstart() {
        return isstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_role.isStart
     *
     * @param isstart the value for as_role.isStart
     *
     * @mbggenerated
     */
    public void setIsstart(Integer isstart) {
        this.isstart = isstart;
    }
}