package com.jbit.dao;

public class AsSystemconfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_systemconfig.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_systemconfig.configType
     *
     * @mbggenerated
     */
    private Integer configtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_systemconfig.configTypeValue
     *
     * @mbggenerated
     */
    private Integer configtypevalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_systemconfig.configTypeName
     *
     * @mbggenerated
     */
    private String configtypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_systemconfig.configValue
     *
     * @mbggenerated
     */
    private String configvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_systemconfig.isStart
     *
     * @mbggenerated
     */
    private Integer isstart;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_systemconfig.id
     *
     * @return the value of as_systemconfig.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_systemconfig.id
     *
     * @param id the value for as_systemconfig.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_systemconfig.configType
     *
     * @return the value of as_systemconfig.configType
     *
     * @mbggenerated
     */
    public Integer getConfigtype() {
        return configtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_systemconfig.configType
     *
     * @param configtype the value for as_systemconfig.configType
     *
     * @mbggenerated
     */
    public void setConfigtype(Integer configtype) {
        this.configtype = configtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_systemconfig.configTypeValue
     *
     * @return the value of as_systemconfig.configTypeValue
     *
     * @mbggenerated
     */
    public Integer getConfigtypevalue() {
        return configtypevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_systemconfig.configTypeValue
     *
     * @param configtypevalue the value for as_systemconfig.configTypeValue
     *
     * @mbggenerated
     */
    public void setConfigtypevalue(Integer configtypevalue) {
        this.configtypevalue = configtypevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_systemconfig.configTypeName
     *
     * @return the value of as_systemconfig.configTypeName
     *
     * @mbggenerated
     */
    public String getConfigtypename() {
        return configtypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_systemconfig.configTypeName
     *
     * @param configtypename the value for as_systemconfig.configTypeName
     *
     * @mbggenerated
     */
    public void setConfigtypename(String configtypename) {
        this.configtypename = configtypename == null ? null : configtypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_systemconfig.configValue
     *
     * @return the value of as_systemconfig.configValue
     *
     * @mbggenerated
     */
    public String getConfigvalue() {
        return configvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_systemconfig.configValue
     *
     * @param configvalue the value for as_systemconfig.configValue
     *
     * @mbggenerated
     */
    public void setConfigvalue(String configvalue) {
        this.configvalue = configvalue == null ? null : configvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_systemconfig.isStart
     *
     * @return the value of as_systemconfig.isStart
     *
     * @mbggenerated
     */
    public Integer getIsstart() {
        return isstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_systemconfig.isStart
     *
     * @param isstart the value for as_systemconfig.isStart
     *
     * @mbggenerated
     */
    public void setIsstart(Integer isstart) {
        this.isstart = isstart;
    }
}