package com.jbit.dao;

public class HatArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hat_area.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hat_area.cityID
     *
     * @mbggenerated
     */
    private Integer cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hat_area.areaID
     *
     * @mbggenerated
     */
    private Integer areaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hat_area.areaName
     *
     * @mbggenerated
     */
    private String areaname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hat_area.id
     *
     * @return the value of hat_area.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hat_area.id
     *
     * @param id the value for hat_area.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hat_area.cityID
     *
     * @return the value of hat_area.cityID
     *
     * @mbggenerated
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hat_area.cityID
     *
     * @param cityid the value for hat_area.cityID
     *
     * @mbggenerated
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hat_area.areaID
     *
     * @return the value of hat_area.areaID
     *
     * @mbggenerated
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hat_area.areaID
     *
     * @param areaid the value for hat_area.areaID
     *
     * @mbggenerated
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hat_area.areaName
     *
     * @return the value of hat_area.areaName
     *
     * @mbggenerated
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hat_area.areaName
     *
     * @param areaname the value for hat_area.areaName
     *
     * @mbggenerated
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname == null ? null : areaname.trim();
    }
}